#!/bin/sh

./autogen.sh
./my-configure mingw
make clean
make -j4
cp src/discordband.exe .
if [ -n "$1" ]
then
    file=discordband-"$1".zip
else
    file=discordband-"$(git describe)".zip
fi

rm $file
find ./lib -name Makefile -prune -o -name .deps -prune -o -print | zip $file -@
zip $file discordband.exe readme.txt
